hawkw/thingbuf

src/mpsc/async_impl.rs
src/mpsc/sync.rs
src/mpsc/tests/mpsc_async.rs
src/mpsc/tests/mpsc_sync.rs
src/static_thingbuf.rs
src/thingbuf.rs
src/util.rs
src/util/wait.rs
tests/debug.rs

feat: add nicer `fmt::Debug` impls

---

src/lib.rs
src/mpsc.rs
src/mpsc/async_impl.rs
src/mpsc/sync.rs
src/mpsc/tests/mpsc_async.rs
src/mpsc/tests/mpsc_sync.rs
src/static_thingbuf.rs
src/stringbuf.rs
src/thingbuf.rs

Errors for `TrySend` now return values.

feat(mpsc): make errors more like other mpscs

---

src/loom.rs
src/macros.rs

This helps a *lot* when a test fails on the 300,000th iteration or
something; you don't have to wait for *every* previous iteration's trace
to be dumped to stdout.

test: loom tests only print traces from the failed iteration

---

.github/workflows/loom.yml
.github/workflows/tests.yml
Cargo.toml
src/lib.rs
src/loom.rs
src/mpsc.rs
src/thingbuf.rs
src/util.rs
src/util/wait/wait_cell.rs

This lets different groups of loom tests run in parallel, which might
make CI runs faster.

chore(ci): split loom tests into separate CI jobs

---

Cargo.toml
README.md
src/lib.rs
src/loom.rs
src/mpsc.rs
src/mpsc/async_impl.rs
src/mpsc/sync.rs
src/mpsc/tests/mpsc_async.rs
src/mpsc/tests/mpsc_sync.rs
src/thingbuf/tests.rs
src/util/wait/wait_cell.rs
src/util/wait/wait_queue.rs

Now that tokio-rs/loom#219 has merged, we can add
`Deref`/`DerefMut` for the `Ref` types without breaking
Loom's concurrent access checking! :D
This makes the `Ref` APIs much easier to work with.

feat: add `Deref` and `DerefMut` impls to `Ref` types

---

src/lib.rs
src/macros.rs
src/mpsc.rs
src/mpsc/async_impl.rs
src/mpsc/sync.rs
src/wait/queue.rs

This fixes a deadlock issue in the async MPSC's `send_ref` method. The
deadlock occurs when a new waker needs to be registered for a task whose
wait node is already in the wait queue. Previously, the new waker would
not be registered because the waker registering closure was only called
when the node was being enqueued. If the node was already in the queue,
polling the future would never touch the waker. This means that if the
task was polled with a new waker, it would leave its old waker in the
queue, and might never be notified again.
This branch fixes that by separating pushing the task and registering
the waker. We check if the node already has a waker prior to registering,
and if it did, we don't push it again.

fix(mpsc): fix a deadlock in async send_ref 

---

Cargo.toml
bench/Cargo.toml
src/lib.rs
src/mpsc.rs
src/mpsc/async_impl.rs
src/mpsc/sync.rs
src/util.rs
src/util/mutex.rs
src/wait.rs
src/wait/cell.rs
src/wait/queue.rs

This branch rewrites the MPSC channel wait queue implementation (again),
in order to improve performance. This undoes a decently large amount of
the perf regression from PR #20.
In particular, I've made the following changes:
* Simplified the design a bit, and reduced the number of CAS loops in
both the notify and wait paths
* Factored out fast paths (which touch the state variable without
locking) from the notify and wait operations into separate functions,
and marked them as `#[inline(always)]`. If we weren't able to perform
the operation without actually touching the linked list, we call into
a separate `#[inline(never)]` function that actually locks the list
and performs the slow path. This means that code that uses these
functions still has a function call in it, but a few …

perf(mpsc): rewrite and optimize wait queue

---

src/lib.rs
src/mpsc/async_impl.rs
src/mpsc/sync.rs
src/static_thingbuf.rs
src/thingbuf.rs

This isn't necessary, as we can use a const while loop
to fill in the slots with correct indices.
This makes the push and pop code a little simpler, which
may also improve performance!

refac: remove special empty state from slots

---

.github/workflows/loom.yml
src/lib.rs
src/mpsc/async_impl.rs
src/mpsc/sync.rs
src/mpsc/tests/mpsc_async.rs
src/mpsc/tests/mpsc_sync.rs
src/static_thingbuf.rs
src/thingbuf.rs
src/wait/queue.rs

This also adds loom leak checking tests. 
I also made `WaitQueue::close` into an RMW op to work around `loom`
not modeling `SeqCst` properly.

fix(mpsc): ensure un-received messages are dropped

---

.github/workflows/miri.yaml
bin/miri
src/mpsc/tests/mpsc_async.rs
src/wait/queue.rs

This branch adds support for running Miri tests against `thingbuf`. The
primary reason to use Miri is for testing the wait queue linked list
implementation. Other unsafe code in `thingbuf` is primarily unsafe due
to potential concurrent access issues (which are tested for using
`loom`), rather than doing anything particularly weird with raw pointers
and lifetimes (for which we would want to use Miri).
In order to actually test the implementation using Miri, I wrote a few
tests that exercise basic functionality for the wait queue. 
In the process, I fixed two issues:
- A potential stacked borrows violation in the `enqueue` operation due
to creating a raw pointer to the node being enqueued while there is also
an `&mut` reference to it. This code doesn't currently result in
anything bad …

test: add Miri tests, fix a stacked borrows violation

---

.github/workflows/lints.yml
.github/workflows/loom.yml
.github/workflows/miri.yaml
.github/workflows/tests.yml

Currently, CI jobs are not triggered when changing their configuration
files. This is not great --- when we change the CI configs, we should
ensure that the CI jobs actually run.
This branch fixes that by adding the CI jobs' config files to the files
that trigger runs when modified.

chore(ci): trigger CI runs when test files change

---

.github/workflows/loom.yml

This cleans up the loom CI config and makes it a bit easier to add new
models. Also, I added an "all loom tests pass" step to make branch
protection easier.

chore(ci): use build matrix for loom CI jobs 

---

.github/workflows/tests.yml
Cargo.toml
README.md
src/lib.rs
src/mpsc/async_impl.rs
src/mpsc/sync.rs
src/static_thingbuf.rs
tests/static_storage.rs

This branch makes Rust 1.57.0 `thingbuf`'s official minimum supported
Rust version. Unfortunately, it was necessary to feature-flag the
`StaticChannel` and `StaticThingBuf` APIs, as they only compile on Rust
1.60.0. This is because the type definitions of the static APIs include
both a const generic _and_ a default type parameter, which is only
possible on 1.60+.

chore: adopt Rust 1.57.0 as MSRV

---

bench/benches/sync_spsc.rs
src/mpsc.rs
src/mpsc/blocking.rs
src/mpsc/tests.rs
src/mpsc/tests/mpsc_blocking.rs
tests/mpsc_blocking.rs
tests/static_storage.rs

This naming scheme should be a bit less ambiguous.

chore: rename `mpsc::sync` to `mpsc::blocking`

---

README.md
src/lib.rs

I haven't quite finished writing this, and it probably deserves to
become a full-fledged blog post. This commit temporarily removes it from
the documentation, because I really want to go ahead and publish v0.1.0
without having to write a bunch more stuff...

docs: temporarily remove MPSC perf comparison

---

src/mpsc/async_impl.rs
src/mpsc/blocking.rs
src/static_thingbuf.rs
src/thingbuf.rs

feat: add `#[must_use]` to constructors

---

src/mpsc.rs
src/mpsc/async_impl.rs

I forgot we already have a dev-dependency on Tokio, so we can use it in
the async examples. This way, the examples actually run, so we know they
are correct.

docs: use real Tokio in async MPSC examples

---

bench/Cargo.toml
bench/benches/async_mpsc_nowait.rs
bench/benches/async_mpsc_utils.rs

These benchmarks measure the case where waiting does *not* occur because
the channel always has cpaacity. This is intended to measure overhead
of wait list implementations.

test(bench): add benchmarks for no-wait cases

---

src/wait/cell.rs
src/wait/queue.rs

It's not actually all that *important* that the private items RustDoc
build correctly, but it's nice for it to work. This commit fixes up
some internal RustDoc links and stuff.

docs: fix up internal RustDoc

---

.github/workflows/tests.yml

Due to a typo, we were accidentally trying to run tests on the operating
system "m". Since GitHub Actions doesn't have runners running the "m"
operating system (because, as far as I know, it doesn't actually
'exist'), this test job would never actually run.
I don't know how this ended up getting merged to main, I really thought
I fixed it on the branch? But, whatever...

chore(ci): remove wrong test job that never ran

---

.github/workflows/tests.yml
src/lib.rs
src/macros.rs
src/mpsc/async_impl.rs
src/util/mutex/spin_impl.rs
src/util/panic.rs

This fixes compilation for no-std targets. My bad --- I was checking
this manually and never added a CI job for it.
This branch adds a CI check that the crate compiles with
`--no-default-features`, and fixes a number of issues that broke the
no-std build:
* f8d9527 fix(no_std): fix warning in `resume_unwind`
* cbf943a fix(no_std): fix compilation error in `unreachable_unchecked`
* 8ae178a fix(no_std): remove use of `thread::panicking`
* dab0d49 fix(alloc): fix missing `Box` imports
* 208defc fix(no_std): wrong feature gate for println macros
Fixes #58

fix: compilation errors with `--no-default-features`

---

src/mpsc.rs
src/mpsc/async_impl.rs
src/mpsc/blocking.rs

`try_recv_ref` should return a `RecvRef` to notify the sender threads to wake up.
@hawkw r?

fix: try_recv_ref should return RecvRef

---

.github/workflows/loom.yml
Cargo.toml
src/mpsc/tests/mpsc_async.rs
src/mpsc/tests/mpsc_blocking.rs

- add a simple test for try_recv_ref
- changes `mpsc_sync ` in `loom.yml` to `mpsc_blocking `, make CI works
- also enable some tests blocked by [tokio-rs/loom#246](https://github.com/tokio-rs/loom/issues/246)

chore: add test for mpsc::try_recv_ref, enable some loom tests

---

CHANGELOG.md
Cargo.toml

<a name="v0.1.3"></a>
* **mpsc:**  add `Receiver::try_recv` method  (#60) ([e04661fc](https://github.com/hawkw/thingbuf/commit/e04661fc72b08c4e2517a9f0bfb16aa7d2fed683))
* **mpsc:**  `try_recv_ref` should return `RecvRef` (#61) ([47f16f59](https://github.com/hawkw/thingbuf/commit/47f16f59579e7a5d11a69c47c4a3b7379b758c75))

chore: prepare to release v0.1.3

---

README.md

Fixes a couple of links in the `README` that are broken since the `sync` module was renamed to `blocking`.

README: fix doc links to blocking module

---

src/lib.rs

This commit fixes the [`clippy::needless_borrow`][1] lints which were added in a recent Clippy version.
[1]: https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

style: fix `clippy::needless_borrow` lints

---

src/mpsc/blocking.rs
src/mpsc/errors.rs
src/thingbuf.rs
src/wait/queue.rs

Added recv_timeout methods for blocking::mpsc::Receiver/StaticReceiver. It requires a simple change from `thread::park` to `thread::park_timeout` & an elapsed time check.
We need this functionality so that our threads can wake up at least once every few seconds to check for control events

feat(blocking::mpsc): add `Receiver::recv(_ref)_timeout` methods

---

CHANGELOG.md
Cargo.toml

<a name=""></a>
* **blocking::mpsc:**  add `Receiver::recv(_ref)_timeout` methods (#75) ([b57ce88a](https://github.com/hawkw/thingbuf/commit/b57ce88ac85cf71b363035249e27f1c91e65f372))

chore: prepare to release v0.1.4

---

README.md
src/mpsc/blocking.rs
src/mpsc/errors.rs

feat(blocking::mpsc): add `Sender::send(_ref)_timeout` methods

---

src/lib.rs
src/mpsc/tests/mpsc_async.rs
src/mpsc/tests/mpsc_blocking.rs

Fixes: https://github.com/hawkw/thingbuf/issues/83
Previously, to determine if the buffer was full, we checked whether the head and tail were pointing to the same slot with the head one generation behind. However, this check fails if we skip slots, leading to scenarios where the `head` and `tail` point to different slots even though the buffer is full.
For example, consider a buffer with 3 slots. Initially, we write to the buffer three times (gen + 0). Then, we read from slot 0 and slot 1, holding the reference from slot 1, and read from slot 2 (gen + 0). Next, we write to slot 0 (gen + 1) and read from slot 0 (gen + 1), which moves our `head` to slot 1 (gen + 1). Then we try to write to slot 1 (gen + 1) and skip it, so we write to slot 2 (gen + 1). Then again we write to slot 0 (gen + …

Fix issue #83: thingbuf hangs when buffer is full
